Repository CS2103-AY1819S1-T09-1/main, pull requests merged in 2018-11, with the labels that each got.

#113 Contacts assigned and tasks assigned commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/CalendarPanelClickEvent.java
  src/main/java/seedu/address/commons/events/ui/JumpToPersonListRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/JumpToTaskListRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/NewResultAvailableEvent.java
  src/main/java/seedu/address/commons/events/ui/PersonPanelDeselectionEvent.java
  src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowHelpRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/TaskPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/commands/contacts/AssignedCommand.java
  src/main/java/seedu/address/logic/commands/tasks/AssignedCommand.java
  src/main/java/seedu/address/logic/parser/ContactsParser.java
  src/main/java/seedu/address/logic/parser/TasksParser.java
  src/main/java/seedu/address/logic/parser/contacts/AssignedCommandParser.java
  src/main/java/seedu/address/logic/parser/contacts/SelectCommandParser.java
  src/main/java/seedu/address/logic/parser/tasks/AssignedCommandParser.java
  src/main/java/seedu/address/model/person/IsAssignedToPersonPredicate.java
  src/main/java/seedu/address/model/task/IsAssignedToTaskPredicate.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/contacts/AssignedCommandTest.java
  src/test/java/seedu/address/logic/parser/ContactsParserTest.java
  src/test/java/seedu/address/logic/parser/contacts/AssignedCommandParserTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/contacts/AssignedCommandSystemTest.java
  src/test/java/systemtests/contacts/ContactsSystemTest.java
Labels: priority.High

#163 Fix common sections of developer guide
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task

#173 Digitise tasks edit and delete sequence diagram and add writeup
  docs/DeveloperGuide.adoc
  docs/images/EditCommand.jpg
  docs/images/EditCommandParser.jpg
  docs/images/EditTaskModelSequenceDiagram.png
  docs/images/EditTaskSequenceDiagram.png
  docs/plantuml/EditTaskModelSequenceDiagram.puml
  docs/plantuml/EditTaskSequenceDiagram.puml
Labels: priority.High

#179 Fixes invalid keyword and tags input for tasks find command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/tasks/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/tasks/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/tasks/FindCommandParserTest.java
Labels: type.Bug
