Repository CS2103-AY1819S1-T09-1/main, pull requests merged in 2018-10, with the labels that each got.

#57 Separate jump to list events for task and person lists
  src/main/java/seedu/address/commons/events/ui/JumpToPersonListRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/JumpToTaskListRequestEvent.java
  src/main/java/seedu/address/logic/commands/contacts/AssignCommand.java
  src/main/java/seedu/address/logic/commands/contacts/SelectCommand.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/test/java/seedu/address/logic/commands/contacts/SelectCommandTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: type.Bug

#58 Add find task by name
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/tasks/FindCommand.java
  src/main/java/seedu/address/logic/parser/TasksParser.java
  src/main/java/seedu/address/logic/parser/tasks/FindCommandParser.java
  src/main/java/seedu/address/model/task/NameContainsKeywordsPredicate.java
Labels: type.Enhancement

#56 Zero-index month when creating Calendar in DateTime
  src/main/java/seedu/address/model/task/DateTime.java
Labels: severity.Medium, type.Bug

#97 Make start date/time optional when adding tasks
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/tasks/AddCommand.java
  src/main/java/seedu/address/logic/parser/tasks/AddCommandParser.java
  src/main/java/seedu/address/model/task/DateTime.java
Labels: priority.Medium, type.Enhancement
